package de.rpi.minecraft.morpheu5.controller;

public enum Command {
	NONE, 
	CHAT_POSTTOCHAT,
	WORLD_GETBLOCK,
	WORLD_GETBLOCKWITHDATA,
	WORLD_SETBLOCK,
	WORLD_SETBLOCKS,
	WORLD_GETHEIGHT,
	WORLD_GETPLAYERIDS,
	WORLD_SETTING,
	WORLD_CHECKPOINT_SAVE,
	WORLD_CHECKPOINT_RESTORE,
	PLAYER_GETPOS
}
